export const spacesConstants = {
  PORTAL: eXo.env.portal.context || '',
  PORTAL_NAME: eXo.env.portal.portalName || '',
  CONTAINER_NAME: eXo.env.portal.containerName || '',
  PORTAL_REST: eXo.env.portal.rest,
  SOCIAL_SPACE_API: `${eXo.env.portal.context}/${eXo.env.portal.rest}/v1/social/spaces/`,
  SOCIAL_SPACES_API: `${eXo.env.portal.context}/${eXo.env.portal.rest}/${eXo.env.portal.containerName}/social/spaces/`,
  SOCIAL_USER_API: `${eXo.env.portal.context}/${eXo.env.portal.rest}/v1/social/users`,
  SPACE_ID: eXo.env.portal.spaceId,
  LANG: eXo.env.portal.language,
  HOST_NAME: window.location.host,
  MANAGERS_ROLE: '/users?role=manager',
  UPLOAD_API: `${eXo.env.portal.context}/upload`,
  MAX_UPLOAD_SIZE: 10,
  MAX_UPLOAD_FILES: 1,
  userName: eXo.env.portal.userName,
  format: 'json',
  typeOfRelation: 'confirmed',
};